version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: 2nit_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  application:
    image: ${2nit_spring:latest}
    container_name: 2nit_spring
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      SSL_PASSWORD: ${SSL_PASSWORD}

      REDIS_HOST: redis
      REDIS_PORT: 6379

    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /home/qowhx12/ssl:/app/ssl:ro
      - /home/qowhx12/swingbench:/app/swingbench:ro

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    depends_on:
      - redis

volumes:
  redis_data: