# 로컬 개발 환경 설정
spring:
  security:
    require-ssl: false  # 로컬 개발에서는 SSL 비활성화


  # DataBase (Oracle - 기본 데이터 저장용)
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${MAIN_DB_URL}
    username: ${MAIN_DB_USERNAME}
    password: ${MAIN_DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource


  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  
  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    com.sys.dbmonitor: DEBUG
    org.apache.coyote.http11: WARN  # HTTP 파싱 오류 로그 레벨 조정

# SSL 비활성화 명시
server:
  ssl:
    enabled: false

