# 프로덕션 환경 설정
server:
  ssl:
    enabled: true
    key-store: /app/ssl/keystore.p12  # Docker 컨테이너 내부 경로
    key-store-type: PKCS12
    key-store-password: ${SSL_PASSWORD}
    key-alias: tomcat



spring:
  security:
    require-ssl: true


  # DataBase (Oracle - 기본 데이터 저장)
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  # Redis Repository 자동 설정 제외 (JPA Repository와 충돌 방지)
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

# SwingBench 설정
swingbench:
  jar:
    path: /app/swingbench/jar/swingbench.jar  # 컨테이너 내부 경로
  ojdbc:
    path: /app/swingbench/jar/ojdbc8.jar