# 로컬 개발 환경 설정
spring:
  security:
    require-ssl: false  # 로컬 개발에서는 SSL 비활성화


  # DataBase
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver  # 최신 방식 (기존 Oracle DB - MyBatis용)
    url: ${WHA_DB_URL}
    username: ${WHA_DB_USERNAME}
    password: ${WHA_DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource

  # PostgreSQL 설정 (TargetDatabase 엔티티 저장용)
  postgres:
    datasource:
      url: ${POSTGRES_DB_URL}
      username: ${POSTGRES_DB_USERNAME}
      password: ${POSTGRES_DB_PASSWORD}


  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  
  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    com.sys.dbmonitor: DEBUG
    org.apache.coyote.http11: WARN  # HTTP 파싱 오류 로그 레벨 조정

# SSL 비활성화 명시
server:
  ssl:
    enabled: false

