spring:
  application:
    name: DBMonitor

  # DataBase
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource

# mybatis sql ??
logging:
  level:
    com:
      sys:
        stm: debug

server:
  port: 8081


mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
  plugins:
    - com.sys.stm.global.common.interceptor.AuditingInterceptor
