-- ============================================
-- metric_data_test 테이블의 Double 타입 컬럼들을 FLOAT(53)으로 변경
-- Hibernate 스키마 검증 오류 해결을 위함
-- ============================================

-- 주의: 데이터가 있는 경우에도 타입 변경이 가능하지만, 
-- 대용량 테이블의 경우 시간이 걸릴 수 있습니다.

ALTER TABLE metric_data_test MODIFY (
    -- CPU 관련
    HOST_CPU_UTIL_PCT FLOAT(53),
    DB_OF_HOST_SHARE_PCT FLOAT(53),
    AAS_TOTAL FLOAT(53),
    
    -- SESSION 관련
    SESSIONS_LIMIT_UTIL_PCT FLOAT(53),
    PROCESSES_USAGE_PCT FLOAT(53),
    SESSIONS_USAGE_PCT FLOAT(53),
    OPEN_CURSORS_MAX_SESSION_PCT FLOAT(53),
    
    -- I/O 관련
    SINGLE_BLOCK_READ_LATENCY_MS FLOAT(53),
    DIRECT_PATH_READ_LATENCY_MS FLOAT(53),
    DIRECT_PATH_WRITE_LATENCY_MS FLOAT(53),
    PHYSICAL_READ_MB_PER_SEC FLOAT(53),
    PHYSICAL_WRITE_MB_PER_SEC FLOAT(53),
    
    -- Wait Class 관련
    WAIT_CLASS_AAS_USER_IO FLOAT(53),
    WAIT_CLASS_AAS_COMMIT FLOAT(53),
    WAIT_CLASS_AAS_CONCURRENCY FLOAT(53),
    WAIT_CLASS_AAS_NETWORK FLOAT(53),
    WAIT_CLASS_AAS_OTHER FLOAT(53),
    
    -- MEMORY 관련
    WORKAREA_SPILL_RATE_PCT FLOAT(53),
    LIBCACHE_RELOAD_PER_S FLOAT(53),
    HARD_PARSES_PER_SEC FLOAT(53),
    SPILL_MB_PER_MIN FLOAT(53),
    
    -- STORAGE 관련
    FRA_USAGE_PCT FLOAT(53),
    SYSTEM_TS_USAGE_PCT FLOAT(53),
    SYSAUX_TS_USAGE_PCT FLOAT(53),
    USERS_TS_USAGE_PCT FLOAT(53),
    UNDO_TS_USAGE_PCT FLOAT(53),
    TEMP_TS_USAGE_PCT FLOAT(53)
);

-- 변경 확인
SELECT 
    column_name,
    data_type,
    data_precision,
    data_scale
FROM user_tab_columns
WHERE table_name = 'METRIC_DATA_TEST'
  AND column_name IN (
    'HOST_CPU_UTIL_PCT', 'DB_OF_HOST_SHARE_PCT', 'AAS_TOTAL',
    'SESSIONS_LIMIT_UTIL_PCT', 'PROCESSES_USAGE_PCT', 'SESSIONS_USAGE_PCT',
    'OPEN_CURSORS_MAX_SESSION_PCT', 'SINGLE_BLOCK_READ_LATENCY_MS',
    'DIRECT_PATH_READ_LATENCY_MS', 'DIRECT_PATH_WRITE_LATENCY_MS',
    'PHYSICAL_READ_MB_PER_SEC', 'PHYSICAL_WRITE_MB_PER_SEC',
    'WAIT_CLASS_AAS_USER_IO', 'WAIT_CLASS_AAS_COMMIT', 'WAIT_CLASS_AAS_CONCURRENCY',
    'WAIT_CLASS_AAS_NETWORK', 'WAIT_CLASS_AAS_OTHER', 'WORKAREA_SPILL_RATE_PCT',
    'LIBCACHE_RELOAD_PER_S', 'HARD_PARSES_PER_SEC', 'SPILL_MB_PER_MIN',
    'FRA_USAGE_PCT', 'SYSTEM_TS_USAGE_PCT', 'SYSAUX_TS_USAGE_PCT',
    'USERS_TS_USAGE_PCT', 'UNDO_TS_USAGE_PCT', 'TEMP_TS_USAGE_PCT'
  )
ORDER BY column_name;

COMMIT;

DBMS_OUTPUT.PUT_LINE('===========================================');
DBMS_OUTPUT.PUT_LINE('Double 컬럼 타입 변경 완료!');
DBMS_OUTPUT.PUT_LINE('NUMBER -> FLOAT(53)');
DBMS_OUTPUT.PUT_LINE('===========================================');

