CREATE TABLE monitoring_metric_data (
                                        id                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                        db_id               NUMBER NOT NULL,
                                        graph_id            NUMBER NOT NULL,
                                        category_id         NUMBER NOT NULL,
                                        collected_at        TIMESTAMP NOT NULL,
                                        created_at          TIMESTAMP DEFAULT SYSDATE NOT NULL,

    -- CPU
                                        host_busy_cores NUMBER, host_total_cores NUMBER, host_cpu_util_pct NUMBER,
                                        aas_oncpu_sessions NUMBER, core_baseline_sessions NUMBER, cpu_saturation_pct NUMBER,
                                        db_of_host_share_pct NUMBER, runq_per_core_load_proxy NUMBER, tps_per_sec NUMBER,
                                        execs_per_sec NUMBER, user_calls_per_sec NUMBER, other_processes_pct NUMBER,
                                        load_threshold NUMBER, load_threshold_min NUMBER, load_threshold_max NUMBER,
                                        cpu_per_commit_ms NUMBER, cpu_per_exec_ms NUMBER, aas_fg_sessions NUMBER, aas_bg_sessions NUMBER,
                                        top_sql_by_cpu_sql_id_01 VARCHAR2(255), top_sql_by_cpu_sql_id_02 VARCHAR2(255),
                                        top_sql_by_cpu_sql_id_03 VARCHAR2(255), top_sql_by_cpu_sql_id_04 VARCHAR2(255),
                                        top_sql_by_cpu_sql_id_05 VARCHAR2(255), top_sql_by_cpu_value_01 NUMBER,
                                        top_sql_by_cpu_value_02 NUMBER, top_sql_by_cpu_value_03 NUMBER, top_sql_by_cpu_value_04 NUMBER,
                                        top_sql_by_cpu_value_05 NUMBER,

    -- SESSION
                                        active_user_sessions_now NUMBER, inactive_user_sessions_now NUMBER, aas_wait_sessions NUMBER,
                                        lock_wait_tx NUMBER, lock_wait_tm NUMBER, lock_wait_total NUMBER, logons_per_sec NUMBER,
                                        disconnects_per_sec NUMBER, total_user_sessions_now NUMBER, active_user_ratio_pct NUMBER,
                                        sessions_used_current NUMBER, sessions_limit NUMBER, sessions_limit_util_pct NUMBER,
                                        processes_current NUMBER, processes_limit NUMBER, processes_limit_util_pct NUMBER,
                                        blockers_now NUMBER, blocked_now NUMBER,
                                        top_blocker_session_name_01 VARCHAR2(255), top_blocker_session_name_02 VARCHAR2(255),
                                        top_blocker_session_name_03 VARCHAR2(255), top_blocker_session_name_04 VARCHAR2(255),
                                        top_blocker_session_name_05 VARCHAR2(255), top_blocker_session_value_01 NUMBER,
                                        top_blocker_session_value_02 NUMBER, top_blocker_session_value_03 NUMBER,
                                        top_blocker_session_value_04 NUMBER, top_blocker_session_value_05 NUMBER,

    -- IO
                                        cache_hit_ratio_pct NUMBER, avg_io_wait_time_ms NUMBER, physical_reads_per_sec NUMBER,
                                        redo_size_mb_per_sec NUMBER, parse_execute_ratio NUMBER, direct_path_io_per_sec NUMBER,
                                        physical_reads_direct_per_sec NUMBER, physical_writes_direct_per_sec NUMBER,
                                        direct_io_ratio_pct NUMBER, parser_request_per_sec NUMBER, sql_execute_per_sec NUMBER,
                                        sql_parse_execute_ratio NUMBER, physical_reads_per_diff_sec NUMBER, logical_reads_per_sec NUMBER,
                                        cache_hit_ratio_diff_pct NUMBER, total_reads_per_sec NUMBER, avg_wait_time_ms NUMBER,
                                        p95_wait_time_ms NUMBER, io_waits_per_sec NUMBER, io_time_per_sec_ms NUMBER,
                                        redo_generation_mbps NUMBER, redo_generation_mbps_total NUMBER, redo_generation_24h_avg NUMBER,
                                        log_switch_count_1min NUMBER, log_switch_count_5min NUMBER, dbwr_write_count_per_min NUMBER,
                                        dbwr_write_volume_mb_per_min NUMBER, dbwr_write_volume_mb_per_min_total NUMBER,
                                        checkpoint_not_complete_count NUMBER, datafile_name_01 VARCHAR2(1024),
                                        datafile_name_02 VARCHAR2(1024), datafile_name_03 VARCHAR2(1024),
                                        datafile_name_04 VARCHAR2(1024), datafile_name_05 VARCHAR2(1024), datatablespace_name_01 VARCHAR2(255),
                                        datatablespace_name_02 VARCHAR2(255), datatablespace_name_03 VARCHAR2(255), datatablespace_name_04 VARCHAR2(255),
                                        datatablespace_name_05 VARCHAR2(255), dataio_share_pct_01 NUMBER, dataio_share_pct_02 NUMBER,
                                        dataio_share_pct_03 NUMBER, dataio_share_pct_04 NUMBER, dataio_share_pct_05 NUMBER,

    -- STORAGE
                                        fra_usage_percent NUMBER, fra_free_gb NUMBER, undo_usage_pct NUMBER, temp_usage_pct NUMBER,
                                        max_ts_name VARCHAR2(255), max_ts_usage_pct NUMBER, total_db_usage_pct NUMBER, temp_active_usage_gb NUMBER,
                                        temp_current_size_gb NUMBER, temp_max_size_gb NUMBER, temp_usage_percent NUMBER, temp_usage_pct_of_max NUMBER,
                                        temp_peak_usage_24h_gb NUMBER, system_tablespace_name VARCHAR2(255), sysaux_tablespace_name VARCHAR2(255),
                                        undotbs1_tablespace_name VARCHAR2(255), users_tablespace_name VARCHAR2(255), system_used_percent NUMBER,
                                        sysaux_used_percent NUMBER, undotbs1_used_percent NUMBER, users_used_percent NUMBER,
                                        system_tablespace_name_inc VARCHAR2(255), sysaux_tablespace_name_inc VARCHAR2(255),
                                        undotbs1_tablespace_name_inc VARCHAR2(255), users_tablespace_name_inc VARCHAR2(255),
                                        system_used_space_gb_inc NUMBER, sysaux_used_space_gb_inc NUMBER, undotbs1_used_space_gb_inc NUMBER,
                                        users_used_space_gb_inc NUMBER, space_limit_gb NUMBER, space_used_gb NUMBER,
                                        space_reclaimable_gb NUMBER, usage_pct NUMBER, hourly_growth_pct NUMBER, time_to_95_pct_hours NUMBER,
                                        undo_tablespace_name VARCHAR2(255), undo_usage_percent NUMBER, long_transaction_count NUMBER,
                                        long_transaction_undo_mb NUMBER, undo_retention_sec NUMBER, owner_seg_01 VARCHAR2(255),
                                        owner_seg_02 VARCHAR2(255), owner_seg_03 VARCHAR2(255), owner_seg_04 VARCHAR2(255), owner_seg_05 VARCHAR2(255),
                                        tablespace_name_seg_01 VARCHAR2(255), tablespace_name_seg_02 VARCHAR2(255), tablespace_name_seg_03 VARCHAR2(255),
                                        tablespace_name_seg_04 VARCHAR2(255), tablespace_name_seg_05 VARCHAR2(255), size_gb_seg_01 NUMBER,
                                        size_gb_seg_02 NUMBER, size_gb_seg_03 NUMBER, size_gb_seg_04 NUMBER, size_gb_seg_05 NUMBER,
                                        compression_seg_01 VARCHAR2(255), compression_seg_02 VARCHAR2(255), compression_seg_03 VARCHAR2(255),
                                        compression_seg_04 VARCHAR2(255), compression_seg_05 VARCHAR2(255),

    -- MEMORY
                                        memory_sort_pct NUMBER, dedicated_sess_cnt NUMBER, parallel_proc_cnt NUMBER,
                                        shared_server_proc_cnt NUMBER, dispatcher_proc_cnt NUMBER, job_proc_cnt NUMBER,
                                        pga_used_bytes NUMBER, pga_target_bytes NUMBER, pga_used_pct NUMBER, workarea_spill_exec NUMBER,
                                        workarea_total_exec NUMBER, workarea_spill_rate_pct NUMBER, buffer_cache_hit_pct NUMBER,
                                        library_cache_hit_pct NUMBER, dictionary_cache_hit_pct NUMBER, latch_hit_pct NUMBER,
                                        redo_buffer_wait_pct NUMBER, large_pool_mb NUMBER, java_pool_mb NUMBER, log_buffer_mb NUMBER,
                                        buffer_cache_mb NUMBER, library_cache_mb NUMBER, dictionary_cache_mb NUMBER, sga_used_bytes NUMBER,
                                        sga_total_bytes NUMBER, sga_util_pct NUMBER, shared_pool_free_bytes NUMBER, shared_pool_bytes NUMBER,
                                        shared_pool_free_pct NUMBER, libcache_reload_per_s NUMBER, buffer_miss_pct NUMBER,
                                        top_sql_by_shared_pool_sql_id_01 VARCHAR2(255), top_sql_by_shared_pool_sql_id_02 VARCHAR2(255),
                                        top_sql_by_shared_pool_sql_id_03 VARCHAR2(255), top_sql_by_shared_pool_sql_id_04 VARCHAR2(255),
                                        top_sql_by_shared_pool_sql_id_05 VARCHAR2(255),
                                        top_sql_by_shared_pool_value_01 NUMBER, top_sql_by_shared_pool_value_02 NUMBER,
                                        top_sql_by_shared_pool_value_03 NUMBER, top_sql_by_shared_pool_value_04 NUMBER,
                                        top_sql_by_shared_pool_value_05 NUMBER,

    -- 기타/커스텀
                                        spill_mb_per_min NUMBER, aas_total NUMBER, wait_class_aas_user_io NUMBER,
                                        wait_class_aas_commit NUMBER, wait_class_aas_concurrency NUMBER, wait_class_aas_system_io NUMBER,
                                        wait_class_aas_network NUMBER, wait_class_aas_cluster NUMBER, wait_class_aas_other NUMBER,
                                        single_block_read_latency_ms NUMBER, direct_path_read_latency_ms NUMBER, direct_path_write_latency_ms NUMBER,
                                        physical_read_mb_per_sec NUMBER, physical_write_mb_per_sec NUMBER, hard_parse_ratio_pct NUMBER,
                                        session_usage_pct NUMBER, session_headroom NUMBER, session_growth_rate_per_min NUMBER,
                                        session_breach_eta_min NUMBER, fra_usage_pct NUMBER, system_ts_usage_pct NUMBER,
                                        sysaux_ts_usage_pct NUMBER, users_ts_usage_pct NUMBER, undo_ts_usage_pct NUMBER, temp_ts_usage_pct NUMBER,
                                        system_ts_used_mb NUMBER, sysaux_ts_used_mb NUMBER, users_ts_used_mb NUMBER, undo_ts_used_mb NUMBER,
                                        temp_ts_used_mb NUMBER, system_ts_free_mb NUMBER, sysaux_ts_free_mb NUMBER, users_ts_free_mb NUMBER,
                                        undo_ts_free_mb NUMBER, temp_ts_free_mb NUMBER, lgwr_pid NUMBER, lgwr_active NUMBER,
                                        dbwr_pid NUMBER, dbwr_active NUMBER, pmon_pid NUMBER, pmon_active NUMBER, smon_pid NUMBER, smon_active NUMBER,
                                        ckpt_pid NUMBER, ckpt_active NUMBER, arcn_pid NUMBER, arcn_active NUMBER, processes_usage_pct NUMBER,
                                        sessions_usage_pct NUMBER, open_cursors_max_session_pct NUMBER, db_files_usage_pct NUMBER,
                                        hard_parses_per_sec NUMBER, library_cache_reloads_per_sec NUMBER,

                                        CONSTRAINT fk_monitoring_metric_graph FOREIGN KEY (graph_id) REFERENCES graph(id)
);
