CREATE TABLE graph (
                         id SERIAL NOT NULL,
                         name VARCHAR(64) NOT NULL,
                         category VARCHAR(32) NOT NULL,          -- ENUM 대신 VARCHAR 쓰는 것이 Oracle에서 안정적
                         info VARCHAR(255) NULL,
                         type VARCHAR(32) NOT NULL,              -- ENUM 대신 VARCHAR
                         created_at TIMESTAMP NOT NULL,
                         updated_at TIMESTAMP NOT NULL,
                         is_deleted BOOLEAN NOT NULL,
                         CONSTRAINT PK_GRAPH PRIMARY KEY (id)
);


-- storage_metric_data
CREATE TABLE storage_metric_data (
                                     id SERIAL PRIMARY KEY,
                                     db_id INT NOT NULL,
                                     graph_id INT NOT NULL,
                                     fra_usage_percent varchar(255),
                                     fra_free_gb varchar(255),
                                     undo_usage_pct varchar(255),
                                     temp_usage_pct varchar(255),
                                     max_ts_name varchar(255),
                                     max_ts_usage_pct varchar(255),
                                     total_db_usage_pct varchar(255),
                                     temp_active_usage_gb varchar(255),
                                     temp_current_size_gb varchar(255),
                                     temp_max_size_gb varchar(255),
                                     temp_usage_percent varchar(255),
                                     temp_usage_pct_of_max varchar(255),
                                     temp_peak_usage_24h_gb varchar(255),
                                     system_tablespace_name varchar(255),
                                     sysaux_tablespace_name varchar(255),
                                     undotbs1_tablespace_name varchar(255),
                                     users_tablespace_name varchar(255),
                                     system_used_percent varchar(255),
                                     sysaux_used_percent varchar(255),
                                     undotbs1_used_percent varchar(255),
                                     users_used_percent varchar(255),
                                     system_tablespace_name_inc varchar(255),
                                     sysaux_tablespace_name_inc varchar(255),
                                     undotbs1_tablespace_name_inc varchar(255),
                                     users_tablespace_name_inc varchar(255),
                                     system_used_space_gb_inc varchar(255),
                                     sysaux_used_space_gb_inc varchar(255),
                                     undotbs1_used_space_gb_inc varchar(255),
                                     users_used_space_gb_inc varchar(255),
                                     space_limit_gb varchar(255),
                                     space_used_gb varchar(255),
                                     space_reclaimable_gb varchar(255),
                                     usage_pct varchar(255),
                                     hourly_growth_pct varchar(255),
                                     time_to_95_pct_hours varchar(255),
                                     undo_tablespace_name varchar(255),
                                     undo_usage_percent varchar(255),
                                     long_transaction_count varchar(255),
                                     long_transaction_undo_mb varchar(255),
                                     undo_retention_sec varchar(255),
                                     total_db_usage_percent varchar(255),
                                     "1_owner_seg" varchar(255),
                                     "2_owner_seg" varchar(255),
                                     "3_owner_seg" varchar(255),
                                     "4_owner_seg" varchar(255),
                                     "5_owner_seg" varchar(255),
                                     "1_tablespace_name_seg" varchar(255),
                                     "2_tablespace_name_seg" varchar(255),
                                     "3_tablespace_name_seg" varchar(255),
                                     "4_tablespace_name_seg" varchar(255),
                                     "5_tablespace_name_seg" varchar(255),
                                     "1_size_gb_seg" varchar(255),
                                     "2_size_gb_seg" varchar(255),
                                     "3_size_gb_seg" varchar(255),
                                     "4_size_gb_seg" varchar(255),
                                     "5_size_gb_seg" varchar(255),
                                     "1_compression_seg" varchar(255),
                                     "2_compression_seg" varchar(255),
                                     "3_compression_seg" varchar(255),
                                     "4_compression_seg" varchar(255),
                                     "5_compression_seg" varchar(255),
                                     created_at timestamp NOT NULL,
                                     FOREIGN KEY (db_id) REFERENCES instance(id),
                                     FOREIGN KEY (graph_id) REFERENCES graph (id)
);

-- memory_metric_data
CREATE TABLE memory_metric_data (
                                    id SERIAL PRIMARY KEY,
                                    db_id INT NOT NULL,
                                    graph_id INT NOT NULL,
                                    memory_sort_pct varchar(255),
                                    dedicated_sess_cnt varchar(255),
                                    parallel_proc_cnt varchar(255),
                                    shared_server_proc_cnt varchar(255),
                                    dispatcher_proc_cnt varchar(255),
                                    job_proc_cnt varchar(255),
                                    pga_used_bytes varchar(255),
                                    pga_target_bytes varchar(255),
                                    pga_used_pct varchar(255),
                                    workarea_spill_exec varchar(255),
                                    workarea_total_exec varchar(255),
                                    workarea_spill_rate_pct varchar(255),
                                    buffer_cache_hit_pct varchar(255),
                                    library_cache_hit_pct varchar(255),
                                    dictionary_cache_hit_pct varchar(255),
                                    latch_hit_pct varchar(255),
                                    redo_buffer_wait_pct varchar(255),
                                    large_pool_mb varchar(255),
                                    java_pool_mb varchar(255),
                                    log_buffer_mb varchar(255),
                                    buffer_cache_mb varchar(255),
                                    library_cache_mb varchar(255),
                                    dictionary_cache_mb varchar(255),
                                    sga_used_bytes varchar(255),
                                    sga_total_bytes varchar(255),
                                    sga_util_pct varchar(255),
                                    shared_pool_free_bytes varchar(255),
                                    shared_pool_bytes varchar(255),
                                    shared_pool_free_pct varchar(255),
                                    libcache_reload_per_s varchar(255),
                                    buffer_miss_pct varchar(255),
                                    top_sql_by_shared_pool_sql_id_01 varchar(255),
                                    top_sql_by_shared_pool_sql_id_02 varchar(255),
                                    top_sql_by_shared_pool_sql_id_03 varchar(255),
                                    top_sql_by_shared_pool_sql_id_04 varchar(255),
                                    top_sql_by_shared_pool_sql_id_05 varchar(255),
                                    top_sql_by_shared_pool_value_01 varchar(255),
                                    top_sql_by_shared_pool_value_02 varchar(255),
                                    top_sql_by_shared_pool_value_03 varchar(255),
                                    top_sql_by_shared_pool_value_04 varchar(255),
                                    top_sql_by_shared_pool_value_05 varchar(255),
                                    created_at timestamp NOT NULL,
                                    FOREIGN KEY (db_id) REFERENCES instance(id),
                                    FOREIGN KEY (graph_id) REFERENCES graph(id)
);



-- main_metric_data
CREATE TABLE main_metric_data (
                                  id SERIAL PRIMARY KEY,
                                  db_id INT NOT NULL,
                                  graph_id INT NOT NULL,
                                  spill_mb_per_min varchar(255),
                                  aas_total varchar(255),
                                  wait_class_aas_user_io varchar(255),
                                  wait_class_aas_commit varchar(255),
                                  wait_class_aas_concurrency varchar(255),
                                  wait_class_aas_system_io varchar(255),
                                  wait_class_aas_network varchar(255),
                                  wait_class_aas_cluster varchar(255),
                                  wait_class_aas_other varchar(255),
                                  single_block_read_latency_ms varchar(255),
                                  direct_path_read_latency_ms varchar(255),
                                  direct_path_write_latency_ms varchar(255),
                                  physical_read_mb_per_sec varchar(255),
                                  physical_write_mb_per_sec varchar(255),
                                  hard_parse_ratio_pct varchar(255),
                                  session_usage_pct varchar(255),
                                  session_headroom varchar(255),
                                  session_growth_rate_per_min varchar(255),
                                  session_breach_eta_min varchar(255),
                                  fra_usage_pct varchar(255),
                                  system_ts_usage_pct varchar(255),
                                  sysaux_ts_usage_pct varchar(255),
                                  users_ts_usage_pct varchar(255),
                                  undo_ts_usage_pct varchar(255),
                                  temp_ts_usage_pct varchar(255),
                                  system_ts_used_mb varchar(255),
                                  sysaux_ts_used_mb varchar(255),
                                  users_ts_used_mb varchar(255),
                                  undo_ts_used_mb varchar(255),
                                  temp_ts_used_mb varchar(255),
                                  system_ts_free_mb varchar(255),
                                  sysaux_ts_free_mb varchar(255),
                                  users_ts_free_mb varchar(255),
                                  undo_ts_free_mb varchar(255),
                                  temp_ts_free_mb varchar(255),
                                  lgwr_pid varchar(255),
                                  lgwr_active varchar(255),
                                  dbwr_pid varchar(255),
                                  dbwr_active varchar(255),
                                  pmon_pid varchar(255),
                                  pmon_active varchar(255),
                                  smon_pid varchar(255),
                                  smon_active varchar(255),
                                  ckpt_pid varchar(255),
                                  ckpt_active varchar(255),
                                  arcn_pid varchar(255),
                                  arcn_active varchar(255),
                                  processes_usage_pct varchar(255),
                                  sessions_usage_pct varchar(255),
                                  open_cursors_max_session_pct varchar(255),
                                  db_files_usage_pct varchar(255),
                                  workarea_spill_rate_pct varchar(255),
                                  hard_parses_per_sec varchar(255),
                                  library_cache_reloads_per_sec varchar(255),
                                  aas_oncpu_sessions varchar(255),
                                  core_baseline_sessions varchar(255),
                                  host_cpu_util_pct varchar(255),
                                  cpu_saturation_pct varchar(255),
                                  library_cache_hit_pct varchar(255),
                                  dictionary_cache_hit_pct varchar(255),
                                  created_at timestamp NOT NULL,
                                  FOREIGN KEY (db_id) REFERENCES instance(id),
                                  FOREIGN KEY (graph_id) REFERENCES graph(id)
);


-- session_metric_data
CREATE TABLE session_metric_data (
                                     id SERIAL PRIMARY KEY,
                                     db_id INT NOT NULL,
                                     graph_id INT NOT NULL,
                                     active_user_sessions_now double precision,
                                     inactive_user_sessions_now double precision,
                                     aas_oncpu_sessions double precision,
                                     aas_wait_sessions double precision,
                                     lock_wait_tx double precision,
                                     lock_wait_tm double precision,
                                     lock_wait_total double precision,
                                     tps_per_sec double precision,
                                     execs_per_sec double precision,
                                     logons_per_sec double precision,
                                     disconnects_per_sec double precision,
                                     total_user_sessions_now double precision,
                                     active_user_ratio_pct double precision,
                                     sessions_used_current double precision,
                                     sessions_limit double precision,
                                     sessions_limit_util_pct double precision,
                                     processes_current double precision,
                                     processes_limit double precision,
                                     processes_limit_util_pct double precision,
                                     blockers_now double precision,
                                     blocked_now double precision,
                                     top_blocker_session_name_01 varchar(255),
                                     top_blocker_session_name_02 varchar(255),
                                     top_blocker_session_name_03 varchar(255),
                                     top_blocker_session_name_04 varchar(255),
                                     top_blocker_session_name_05 varchar(255),
                                     top_blocker_session_value_01 double precision,
                                     top_blocker_session_value_02 double precision,
                                     top_blocker_session_value_03 double precision,
                                     top_blocker_session_value_04 double precision,
                                     top_blocker_session_value_05 double precision,
                                     created_at timestamp NOT NULL,
                                     FOREIGN KEY (db_id) REFERENCES instance(id),
                                     FOREIGN KEY (graph_id) REFERENCES graph(id)
);

-- cpu_metric_data
CREATE TABLE cpu_metric_data (
                                 id SERIAL PRIMARY KEY,
                                 db_id INT NOT NULL,
                                 graph_id INT NOT NULL,
                                 host_busy_cores varchar(255),
                                 host_total_cores varchar(255),
                                 host_cpu_util_pct varchar(255),
                                 aas_oncpu_sessions varchar(255),
                                 core_baseline_sessions varchar(255),
                                 cpu_saturation_pct varchar(255),
                                 db_of_host_share_pct varchar(255),
                                 runq_per_core_load_proxy varchar(255),
                                 tps_per_sec varchar(255),
                                 execs_per_sec varchar(255),
                                 user_calls_per_sec varchar(255),
                                 other_processes_pct varchar(255),
                                 load_threshold varchar(255),
                                 load_threshold_min varchar(255),
                                 load_threshold_max varchar(255),
                                 cpu_per_commit_ms varchar(255),
                                 cpu_per_exec_ms varchar(255),
                                 aas_fg_sessions varchar(255),
                                 aas_bg_sessions varchar(255),
                                 top_sql_by_cpu_sql_id_01 varchar(255),
                                 top_sql_by_cpu_sql_id_02 varchar(255),
                                 top_sql_by_cpu_sql_id_03 varchar(255),
                                 top_sql_by_cpu_sql_id_04 varchar(255),
                                 top_sql_by_cpu_sql_id_05 varchar(255),
                                 top_sql_by_cpu_value_01 varchar(255),
                                 top_sql_by_cpu_value_02 varchar(255),
                                 top_sql_by_cpu_value_03 varchar(255),
                                 top_sql_by_cpu_value_04 varchar(255),
                                 top_sql_by_cpu_value_05 varchar(255),
                                 created_at timestamp NOT NULL,
                                 FOREIGN KEY (db_id) REFERENCES instance(id),
                                 FOREIGN KEY (graph_id) REFERENCES graph(id)
);


-- io_metric_data
CREATE TABLE io_metric_data (
                                id SERIAL PRIMARY KEY,
                                db_id INT NOT NULL,
                                graph_id INT NOT NULL,
                                cache_hit_ratio_pct varchar(255),
                                avg_io_wait_time_ms varchar(255),
                                physical_reads_per_sec varchar(255),
                                redo_size_mb_per_sec varchar(255),
                                parse_execute_ratio varchar(255),
                                direct_path_io_per_sec varchar(255),
                                physical_reads_direct_per_sec varchar(255),
                                physical_writes_direct_per_sec varchar(255),
                                direct_io_ratio_pct varchar(255),
                                parser_request_per_sec varchar(255),
                                sql_execute_per_sec varchar(255),
                                sql_parse_execute_ratio varchar(255),
                                physical_reads_per_diff_sec varchar(255),
                                logical_reads_per_sec varchar(255),
                                cache_hit_ratio_diff_pct varchar(255),
                                total_reads_per_sec varchar(255),
                                avg_wait_time_ms varchar(255),
                                p95_wait_time_ms varchar(255),
                                io_waits_per_sec varchar(255),
                                io_time_per_sec_ms varchar(255),
                                redo_generation_mbps varchar(255),
                                redo_generation_mbps_total varchar(255),
                                redo_generation_24h_avg varchar(255),
                                log_switch_count_1min varchar(255),
                                log_switch_count_5min varchar(255),
                                dbwr_write_count_per_min varchar(255),
                                dbwr_write_volume_mb_per_min varchar(255),
                                dbwr_write_volume_mb_per_min_total varchar(255),
                                checkpoint_not_complete_count varchar(255),
                                "1_data_file_name" varchar(255),
                                "2_data_file_name" varchar(255),
                                "3_data_file_nameField3" varchar(255),
                                "4_data_file_name" varchar(255),
                                "5_data_file_name" varchar(255),
                                "1_data_tablespace_name" varchar(255),
                                "2_data_tablespace_name" varchar(255),
                                "3_data_tablespace_name" varchar(255),
                                "4_data_tablespace_name" varchar(255),
                                "5_data_tablespace_name" varchar(255),
                                "1_data_io_share_pct" varchar(255),
                                "2_data_io_share_pct" varchar(255),
                                "3_data_io_share_pct" varchar(255),
                                "4_data_io_share_pct" varchar(255),
                                "5_data_io_share_pct" varchar(255),
                                created_at timestamp NOT NULL,
                                FOREIGN KEY (db_id) REFERENCES instance(id),
                                FOREIGN KEY (graph_id) REFERENCES graph(id)
);