-- DB_INFO 시퀀스
DROP SEQUENCE SEQ_DB_INFO_ID;

CREATE SEQUENCE SEQ_DB_INFO_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOCACHE
    NOCYCLE;

-- INSTANCE 시퀀스
DROP SEQUENCE SEQ_INSTANCE_ID;

CREATE SEQUENCE SEQ_INSTANCE_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOCACHE
    NOCYCLE;

-- MEMBER_WIDGET 시퀀스
DROP SEQUENCE SEQ_MEMBER_WIDGET_ID;

CREATE SEQUENCE SEQ_MEMBER_WIDGET_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOCACHE
    NOCYCLE;

-- GRAPH 시퀀스
DROP SEQUENCE SEQ_GRAPH_ID;

CREATE SEQUENCE SEQ_GRAPH_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOCACHE
    NOCYCLE;

-- METRIC_DATA 시퀀스
DROP SEQUENCE SEQ_METRIC_DATA_ID;

CREATE SEQUENCE SEQ_METRIC_DATA_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOCACHE
    NOCYCLE;

-- MEMBER_WIDGET 시퀀스
DROP SEQUENCE SEQ_MEMBER_ID;

CREATE SEQUENCE SEQ_MEMBER_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOCACHE
    NOCYCLE;
