-- ============================================
-- AAS_ONCPU_SESSIONS 메트릭 템플릿 수정
-- THRESHOLD_FORMAT를 PERCENT에서 COUNT로 변경
-- 임계값도 세션 개수 기준으로 변경
-- ============================================

-- 1. ALERT_METRIC_TEMPLATE 테이블 업데이트
UPDATE ALERT_METRIC_TEMPLATE
SET 
    THRESHOLD_FORMAT = 'COUNT',
    DEFAULT_WARNING = 10.0,
    DEFAULT_DANGER = 20.0,
    DEFAULT_CRITICAL = 30.0,
    DESCRIPTION = 'On-CPU 세션 개수 (AAS_ONCPU_SESSIONS)',
    UPDATED_AT = SYSDATE
WHERE 
    METRIC_KEY = 'AAS_ONCPU_SESSIONS'
    AND IS_DELETED = 0;

-- 2. 기존에 생성된 ALERT_EVENT 규칙도 업데이트 (선택사항)
-- 주의: 기존 정책의 임계값도 변경되므로, 필요시 수동으로 조정해야 할 수 있습니다.
UPDATE ALERT_EVENT
SET 
    THRESHOLD_FORMAT = 'COUNT',
    WARNING = 10.0,
    DANGER = 20.0,
    CRITICAL = 30.0,
    UPDATED_AT = SYSDATE
WHERE 
    METRIC_KEY = 'AAS_ONCPU_SESSIONS'
    AND IS_DELETED = 0
    AND THRESHOLD_FORMAT = 'PERCENT';

-- 3. 변경 사항 확인
SELECT 
    ID,
    METRIC_KEY,
    METRIC_NAME,
    THRESHOLD_FORMAT,
    DEFAULT_WARNING,
    DEFAULT_DANGER,
    DEFAULT_CRITICAL,
    DESCRIPTION
FROM 
    ALERT_METRIC_TEMPLATE
WHERE 
    METRIC_KEY = 'AAS_ONCPU_SESSIONS';

-- 4. 기존 정책 확인 (필요시)
SELECT 
    AE.ID,
    AE.NAME,
    AE.METRIC_KEY,
    AE.THRESHOLD_FORMAT,
    AE.WARNING,
    AE.DANGER,
    AE.CRITICAL,
    AP.NAME AS POLICY_NAME
FROM 
    ALERT_EVENT AE
    INNER JOIN ALERT_POLICY AP ON AE.POLICY_ID = AP.ID
WHERE 
    AE.METRIC_KEY = 'AAS_ONCPU_SESSIONS'
    AND AE.IS_DELETED = 0
    AND AP.IS_DELETED = 0;

